Merged in feature/TEAMS-2447-videoserver-post-install-phas (pull request #2)
[TEAMS-2447] Fix issue with debconf postinstall interactive setup

* [TEAMS-2447] Fix issue with debconf postinstall interactive setup

diff --git a/thirdparty/videoserver/zimbra-videoserver/debian/zimbra-videoserver.postrm b/thirdparty/videoserver/zimbra-videoserver/debian/zimbra-videoserver.postrm
--- a/thirdparty/videoserver/zimbra-videoserver/debian/zimbra-videoserver.postrm
+++ b/thirdparty/videoserver/zimbra-videoserver/debian/zimbra-videoserver.postrm
@@ -1,24 +1,28 @@
 #!/bin/sh
 set -e
-
-# Need to load this before any output on stdout/stderr
-# otherwise the debconf command-stream will get
-# some invalid input and cause the failure of postrm.
-if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
-    . /usr/share/debconf/confmodule
-fi
+. /usr/share/debconf/confmodule
 
 if [ "$1" = "purge" ]; then
-    if getent passwd videoserver >/dev/null; then
-        if which deluser >/dev/null; then
-            deluser --system videoserver || echo "Could not remove videoserver user."
-        fi
+  if getent passwd videoserver >/dev/null; then
+    if which deluser >/dev/null; then
+      deluser --system videoserver || echo "Could not remove videoserver user."
     fi
-    if getent group videoserver >/dev/null; then
-        if which delgroup >/dev/null; then
-            delgroup --system videoserver || echo "Could not remove videoserver group."
-        fi
+  fi
+  if getent group videoserver >/dev/null; then
+    if which delgroup >/dev/null; then
+      delgroup --system videoserver || echo "Could not remove videoserver group."
     fi
+  fi
+
+  hostname=$(hostname -f)
+  db_subst videoserver/remove HOSTNAME "${hostname}"
+  db_input high videoserver/remove || true
+  db_get videoserver/remove
+  db_go
+
+  db_purge
 fi
 
 #DEBHELPER#
+
+exit 0
